//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserService.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserService.Validators.ErrorsMessages", typeof(ErrorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday must not be empty..
        /// </summary>
        public static string BirthdayEmpty {
            get {
                return ResourceManager.GetString("BirthdayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are too young.
        /// </summary>
        public static string BirthdayYoung {
            get {
                return ResourceManager.GetString("BirthdayYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty..
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login length up to 50 characters.
        /// </summary>
        public static string EmailTooLong {
            get {
                return ResourceManager.GetString("EmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must not be empty..
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must not be empty..
        /// </summary>
        public static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first letter must be uppercase and the rest must be lowercase. First name must contain only letters..
        /// </summary>
        public static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long.
        /// </summary>
        public static string FirstNameTooLong {
            get {
                return ResourceManager.GetString("FirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too short.
        /// </summary>
        public static string FirstNameTooShort {
            get {
                return ResourceManager.GetString("FirstNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is null or empty.
        /// </summary>
        public static string IdIsNullOrEmpty {
            get {
                return ResourceManager.GetString("IdIsNullOrEmpty", resourceCulture);
        ///   Looks up a localized string similar to Id must be not empty.
        /// </summary>
        public static string IdEmpty {
            get {
                return ResourceManager.GetString("IdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be not null.
        /// </summary>
        public static string IdNull {
            get {
                return ResourceManager.GetString("IdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address must be in valid format..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must not be empty..
        /// </summary>
        public static string LastNameEmpty {
            get {
                return ResourceManager.GetString("LastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first letter must be uppercase and the rest must be lowercase. Last name must contain only letters.
        /// </summary>
        public static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long.
        /// </summary>
        public static string LastNameTooLong {
            get {
                return ResourceManager.GetString("LastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too short.
        /// </summary>
        public static string LastNameTooShort {
            get {
                return ResourceManager.GetString("LastNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and new passwords are equal.
        /// </summary>
        public static string OldAndNewPasswordsEqual {
            get {
                return ResourceManager.GetString("OldAndNewPasswordsEqual", resourceCulture);
            }
        }
    }
}
