CREATE TABLE dbo.UsersAvatars (
	[Id] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	Avatar VARBINARY(MAX) NOT NULL,
	TypeAvatar NVARCHAR(20) NOT NULL,
	CONSTRAINT [PK_UserAvatars] PRIMARY KEY ([Id] ASC)
)
GO
ALTER TABLE dbo.Users ADD UserAvatarId UNIQUEIDENTIFIER
GO
ALTER TABLE dbo.Users ADD CONSTRAINT
	FK_Users_UsersAvatars FOREIGN KEY
	(
	UserAvatarId
	) REFERENCES dbo.UsersAvatars
	(
	Id
	) ON UPDATE NO ACTION
	ON DELETE NO ACTION
GO