CREATE TABLE dbo.UserAvatars (
	[Id] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	Avatar VARBINARY(MAX) NOT NULL,
	TypeAvatar NVARCHAR(20) NOT NULL,
	CONSTRAINT [PK_UserAvatars] PRIMARY KEY ([Id] ASC)
)
GO
ALTER TABLE dbo.UserAvatars ADD CONSTRAINT
	FK_UserAvatars_Users FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE NO ACTION
	ON DELETE NO ACTION
GO