CREATE TABLE dbo.Portfolio (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Figi] VARCHAR(12) NOT NULL,
	[Lots] INT NOT NULL,

	CONSTRAINT [PK_Portfolio] PRIMARY KEY ([Id] ASC),
	CONSTRAINT FK_Portfolio_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
GO