CREATE TABLE dbo.Portfolios (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Figi] VARCHAR(12) NOT NULL,
	[Count] INT NOT NULL,
	[Broker] VARCHAR(30) NOT NULL,

	CONSTRAINT [PK_Portfolios] PRIMARY KEY ([Id] ASC),

	CONSTRAINT FK_Portfolios_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
GO