CREATE TABLE dbo.TinkoffUsers (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[BalanceInRub] DECIMAL NOT NULL, 
	[BalanceInUsd] DECIMAL NOT NULL, 
	[BalanceInEur] DECIMAL NOT NULL, 
	CONSTRAINT [PK_TinkoffUsers] PRIMARY KEY ([Id] ASC),

	CONSTRAINT FK_TinkoffUsers_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
GO