CREATE TABLE dbo.TinkoffUsers (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[PortfolioId] UNIQUEIDENTIFIER NOT NULL,
	[BalanceInRub] DECIMAL, 
	[BalanceInUsd] DECIMAL, 
	[BalanceInEur] DECIMAL, 
	CONSTRAINT [PK_TinkoffUsers] PRIMARY KEY ([Id] ASC),

	CONSTRAINT FK_TinkoffUsers_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,

	CONSTRAINT FK_TinkoffUsers_Portfolio FOREIGN KEY (UserId) 
	REFERENCES dbo.Portfolio (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
)
GO