CREATE TABLE dbo.UserBalances (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[BalanceInRub] DECIMAL NOT NULL, 
	[BalanceInUsd] DECIMAL NOT NULL, 
	[BalanceInEur] DECIMAL NOT NULL, 
	CONSTRAINT [PK_UserBalances] PRIMARY KEY ([Id] ASC),

	CONSTRAINT FK_UserBalances_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
GO