CREATE TABLE dbo.BrokerUsers (
	[Id] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Broker] VARCHAR(30) NOT NULL,
	[BalanceInRub] DECIMAL NOT NULL, 
	[BalanceInUsd] DECIMAL NOT NULL, 
	[BalanceInEur] DECIMAL NOT NULL, 
	CONSTRAINT [PK_BrokerUsers] PRIMARY KEY ([Id] ASC),

	CONSTRAINT FK_BrokerUsers_Users FOREIGN KEY (UserId) 
	REFERENCES dbo.Users (Id) 
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
GO