CREATE TABLE dbo.LinkBotsWithRules (
    [Id]		    UNIQUEIDENTIFIER NOT NULL   UNIQUE CLUSTERED,
	[IdBot]			UNIQUEIDENTIFIER NOT NULL,
    [IdRule]	    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_LinkBotsWithRules] PRIMARY KEY ([Id] ASC)
)
GO
ALTER TABLE dbo.LinkBotsWithRules ADD CONSTRAINT
	FK_LinkBotsWithRules_IdBot FOREIGN KEY
	(
	IdBot
	) REFERENCES dbo.Bots
	(
	Id
	) ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION
GO
ALTER TABLE dbo.LinkBotsWithRules ADD CONSTRAINT
	FK_LinkBotsWithRules_IdRule FOREIGN KEY
	(
	IdRule
	) REFERENCES dbo.BotRules
	(
	Id
	) ON UPDATE  NO ACTION
	 ON DELETE  NO ACTION
GO